#!/usr/bin/env bash
# Transfer file from host to server!
if [ $# -ne 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    #scp [OPTION] [user@]SRC_HOST:]file1 [user@]DEST_HOST:]file2
    scp -i "$4" "$1" "$3@$2":~/
fi
