#!/usr/bin/env bash
# Installing Nginx

sudo apt -y update
sudo apt -y install nginx
sudo ufw allow "Nginx HTTP"
sudo sh -c 'echo "Holberton School" > /var/www/html/index.nginx-debian.html'
sudo service nginx restart
