#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
i=1
until [ $i -gt 9 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	fi
	if [ $i -eq 7 ]
	then
		echo "good luck"
	fi
	if [ $i -ne 4 ] | [ $i -ne 8 ]
	then
		echo "Holberton School"
	fi
	
	((i++))
done
