#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
i=1
while [ "$i" -lt 10 ]
do
	if [ "$i" -eq 4 ]; then
		echo "bad luck"
	elif [ "$i" -eq 7 ]; then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	((i += 1))
done
